version: '3'

networks:
  laravel:

services:
  nginx_demo:
    image: nginx:stable-alpine
    container_name: nginx_demo
    ports:
      - "8089:80"
      - "4431:443"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - php_demo

  php_demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_demo
    volumes:
      - .:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - laravel


